[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "dockerfile"
file-types = ["Dockerfile", "Dockerfile.lambda"]
auto-format = true

[[language]]
name = "python"
language-server = { command = "pylsp" }
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[language.config.pylsp.plugins]
pyflakes = { enabled = false }
mccabe = { enabled = false }
pyls_isort = { enabled = false }
pycodestyle = { enabled = false, maxLineLength = 88 }
pydocstyle = { enabled = false }
autopep8 = { enabled = false }
yapf = { enabled = false }
flake8 = { enabled = false }
pylint = { enabled = false }
ruff = { enabled = true, extendSelect = ["I"] }
mypy = { enabled = true, live_mode = true, strict = true }
